package com.example.demo;

import javax.swing.*;
import java.awt.*;

public class ShoppingList extends JFrame {
    private JPanel shoppingListMainFrame;

    public ShoppingList() {
        super();
        this.setSize(800, 400);
        this.setBounds(300, 50, 900, 700);
        this.setContentPane(shoppingListMainFrame);
        this.setVisible(true);

    }

    ;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        shoppingListMainFrame = new JPanel();
        shoppingListMainFrame.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        shoppingListMainFrame.setBackground(new Color(-15946596));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return shoppingListMainFrame;
    }
}
