package com.example.demo;

import javax.swing.*;
import java.awt.*;

public class WeeklyMenu extends JFrame {
    private JPanel mainWeeklyMenuFrame;

    public WeeklyMenu() {
        super();
        //this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setSize(800, 400);
        this.setBounds(300, 50, 900, 700);
        this.setContentPane(mainWeeklyMenuFrame);
        this.setVisible(true);

    }

    ;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainWeeklyMenuFrame = new JPanel();
        mainWeeklyMenuFrame.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        mainWeeklyMenuFrame.setBackground(new Color(-15946596));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainWeeklyMenuFrame;
    }

}
